apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: rrafet-web-flask
  labels: 
    app: web-flask
  namespace: demo
spec:
  replicas: 3 
  selector:  
    matchLabels:
      app: web-flask
  minReadySeconds: 10 
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1 
  template: 
    metadata:
      labels:
        app: web-flask
    spec:
      containers:
      - name: rrafet-pod
        image: clarusway/cw_web_flask1
        ports:
        - containerPort: 5000