apiVersion: apps/v1
kind: Deployment
metadata:
  name: rrafet-deploy
  labels:
    environment: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: rrafetnginx
        image: nginx:1.19
        ports:
        - containerPort: 80